version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unparam
    - unused

  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
    gocyclo:
      min-complexity: 20
    godox:
      keywords:
        - FIXME
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: indent-error-flow
        - name: unused-receiver
  exclusions:
    rules:
      - path: example/
        linters:
          - revive
          - gocritic
          - gocyclo

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
